{% set version = "6.3.2" %}
{% set build = 0 %}

package:
  name: rocr-runtime
  version: {{ version }}

build:
  number: {{ build }}
  string: h{{ PKG_HASH }}_{{ build }}
  skip: true  # [win or osx]
  run_exports:
    - {{ pin_compatible('rocr-runtime', max_pin='x.x.x') }}

source:
  git_url: https://github.com/ROCm/ROCR-Runtime.git
  git_rev: rocm-{{ version }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - ninja
    - pkgconfig
  host:
    - elfutils
    - libdrm
    - libnuma
    - rocm-core {{ version }}
    - rocm-device-libs {{ version }}
    - rocm-llvm-tools {{ version }}

test:
  commands:
    - ls -la $PREFIX/lib

about:
  home: https://github.com/ROCm/ROCR-Runtime
  license: NCSA
  license_file: LICENSE
  summary: ROCm HSA Runtime and Support Libraries.

extra:
  recipe-maintainers:
    - j34n
