{% set version = "6.3.2" %}
{% set build = 0 %}

package:
  name: rocm-hip
  version: {{ version }}

build:
  number: {{ build }}
  string: h{{ PKG_HASH }}_{{ build }}
  skip: true  # [win or osx]
  noarch: generic

source:
  git_url: https://github.com/ROCm/HIP.git
  git_rev: rocm-6.3.2

requirements:
  build:
    - cmake >=3.16.8
    - ninja
    - {{ compiler('c') }}
  host:
    - rocm-core {{ version }}
    - rocm-llvm-tools {{ version }}
  run:
    - rocm-core {{ version }}

test:
  commands:
    - test -f $PREFIX/opt/rocm/include/hip/hip_runtime.h
    - test -f $PREFIX/opt/rocm/bin/hipcc || true

about:
  home: https://github.com/ROCm/HIP
  license: MIT
  license_file: LICENSE 
  summary: Portable Heterogeneous-compute Interface for Portability (HIP) API
  description: |
    This package provides the portable HIP API for GPU-accelerated programming
    on AMD and NVIDIA platforms, including headers (e.g., hip/hip_runtime.h)
    and the hipcc driver script. It is part of the ROCm ecosystem, built from
    the ROCm/HIP repository, and serves as the interface layer for HIP
    development.
  doc_url: https://rocm.docs.amd.com/projects/hip/en/latest/
  dev_url: https://github.com/ROCm/HIP

extra:
  recipe-maintainers:
    - j34n
