{% set version = "6.3.2" %}
{% set build = 0 %}

package:
  name: rocm-hip-libraries
  version: {{ version }}

build:
  number: {{ build }}
  string: h{{ PKG_HASH }}_{{ build }}
  skip: true  # [win or osx]
  run_exports:
    - {{ pin_compatible('rocm-hip-libraries', max_pin='x.x.x') }}

source:
  url: https://github.com/ROCm/clr/archive/refs/tags/rocm-{{ version }}.tar.gz
  sha256: ec13dc4ffe212beee22171cb2825d2b16cdce103c835adddb482b9238cf4f050

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - rocm-llvm {{ version }}
  host:
    - rocm-core {{ version }}
    - rocm-device-libs {{ version }}
  run:
    - rocm-core {{ version }}
    - rocm-device-libs {{ version }}

test:
  commands:
    - hipcc --version

about:
  home: https://github.com/ROCm/HIP
  license: MIT
  license_file: LICENSE.TXT
  summary: ROCm HIP (Heterogeneous-compute Interface for Portability) provides a C++ programming environment for AMD GPUs.

extra:
  recipe-maintainers:
    - j34n
