{% set version = "6.3.2" %}
{% set build = 0 %}

package:
  name: rocm-hipcc
  version: {{ version }}

build:
  number: {{ build }}
  string: h{{ PKG_HASH }}_{{ build }}
  skip: true  # [win or osx]
  run_exports:
    - {{ pin_compatible('rocm-hipcc', max_pin='x.x.x') }}
  script_env:
    - ROCM_VERSION={{ version }}

source:
  url: https://github.com/ROCm/llvm-project/archive/refs/tags/rocm-{{ version }}.tar.gz
  sha256: 1f52e45660ea508d3fe717a9903fe27020cee96de95a3541434838e0193a4827

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja
    - rocm-llvm {{ version }}
  run:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - rocm-llvm {{ version }}

test:
  commands:
    - test -x $PREFIX/bin/hipcc
    - test -x $PREFIX/bin/hipconfig

about:
  home: https://github.com/ROCm/llvm-project/tree/amd-staging/amd/hipcc
  license: MIT
  license_file: LICENSE
  summary: ROCm HIP compiler driver.

extra:
  recipe-maintainers:
    - j34n
